spring:
  mvc:
    view:
      suffix:
        .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sys # db url
    username: root
    password: 1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true


